application: gdg-endpoint-demo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /images
  static_dir: images

- url: /style\.css
  static_files: static/style.css
  upload: static/style\.css

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /demo.js
  static_files: static/demo.js
  upload: static/demo\.js
  
- url: /
  static_files: static/demo.html
  upload: static/demo\.html

- url: /_ah/spi/.*
  script: api.application
